version: '3'

services:
  spark-master:
    image: apache/spark:3.5.4-scala2.12-java11-python3-ubuntu
    ports:
      - "8080:8080"      # Spark Master UI
      - "7077:7077"      # Spark Master port
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    command: "/opt/spark/bin/spark-class org.apache.spark.deploy.master.Master"
    container_name: spark-master
    volumes:
      - ./data:/data

  spark-worker:
    image: apache/spark:3.5.4-scala2.12-java11-python3-ubuntu
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=3
      - SPARK_WORKER_MEMORY=4G
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    command: "/opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077"
    deploy:
      replicas: 3
    volumes:
      - ./data:/data

  jupyter-spark:
    build: .
    ports:
      - "8888:8888"      # Jupyter
      - "4040-4050:4040-4050"      # Spark UI
    volumes:
      - ./workspace:/workspace
      - ./data:/data
    environment:
      - JUPYTER_ENABLE_LAB=yes    # Enable JupyterLab
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_DRIVER_MEMORY=2g
      - SPARK_EXECUTOR_MEMORY=4g
      - JUPYTER_TOKEN=token-uag
    depends_on:
      - spark-master
      - spark-worker
      - kafka
    container_name: jupyter-spark

  # ZooKeeper and Kafka using Confluent images
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    volumes:
      - ./data/kafka:/var/lib/kafka/data